export const FRESH_DATA_CLIENT_ERROR = 'FRESH_DATA_CLIENT_ERROR';
export const FRESH_DATA_CLIENT_RECEIVED = 'FRESH_DATA_CLIENT_RECEIVED';
export const FRESH_DATA_CLIENT_REQUESTED = 'FRESH_DATA_CLIENT_REQUESTED';
